# Generated by Django 5.1 on 2024-08-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='parent',
            field=models.TextField(blank=True, max_length=63),
        ),
        migrations.AlterField(
            model_name='component',
            name='description',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.TextField(max_length=63),
        ),
        migrations.AlterField(
            model_name='component',
            name='type',
            field=models.TextField(max_length=63),
        ),
        migrations.AlterField(
            model_name='component',
            name='version',
            field=models.TextField(max_length=7),
        ),
    ]
