# Generated by Django 5.1 on 2024-08-21 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_component_parent_alter_component_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='skeleton',
            field=models.TextField(
                default=models.TextField(max_length=63),
                max_length=25
            ),
        ),
        migrations.AlterField(
            model_name='component',
            name='parent',
            field=models.IntegerField(blank=True),
        ),
        migrations.CreateModel(
            name='MassProperty',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('csys_name', models.TextField(max_length=255)),
                ('is_csys_local', models.BooleanField()),
                ('component', models.IntegerField()),
                ('xform_matrix', models.TextField(blank=True)),
                ('position', models.TextField(blank=True)),
                ('mass', models.TextField(blank=True)),
                ('cog_lsl', models.TextField(blank=True)),
                ('cog_usl', models.TextField(blank=True)),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL
                )),
            ],
        ),
    ]
