# Generated by Django 5.1 on 2024-08-21 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_component_parent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MassProperty',
            new_name='MassProperties',
        ),
    ]
