# Generated by Django 5.1 on 2024-08-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_massproperty_massproperties'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='mass_properties',
            field=models.ManyToManyField(
                related_name='+',
                to='core.massproperties'
            ),
        ),
    ]
