# Generated by Django 5.1 on 2024-08-21 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_component_mass_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massproperties',
            name='component',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='core.component'
            ),
        ),
    ]
