# Generated by Django 5.1 on 2024-08-21 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_massproperties_component'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massproperties',
            name='component',
        ),
    ]
