# Generated by Django 5.1 on 2024-08-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_component_mass_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='mass_properties',
            field=models.ManyToManyField(
                related_name='+',
                to='core.massproperties'
            ),
        ),
    ]
