# Generated by Django 5.1 on 2024-08-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_component_mass_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='mass_properties',
            field=models.ManyToManyField(to='core.massproperties'),
        ),
    ]
